version: "3"
services:
    db:
        image: "mcr.microsoft.com/mssql/server:2017-latest-ubuntu"
        container_name: "SQL2017"
        ports:
          - "1433:1433"
        environment:
            SA_PASSWORD: "S1t3kC0d3@!"
            ACCEPT_EULA: "Y"